name: CI

on:
  push:
    branches:
    - master
  pull_request:
  # enable manual trigger
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.20.x, 1.19.x, 1.18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: ./test
    - name:
      run: cd v2 && ./test
